version: "3"

services:
  apache:
    build:
      context: ./build/apache
      args:
        APACHE_UID: 1000
        APACHE_GID: 1000
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/:Z

  php:
    build: "./build/php/"
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/:Z

  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupalpw
      - MYSQL_ROOT_PASSWORD=drupalpw
    volumes:
      - ./mysql_data:/var/lib/mysql

networks:
  frontend:
  backend: